# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        dialog: 1
        dialogue: 1
        model compression: 2
        BERT: 1
        dialogue state tracking: 2
        transformer: 1
# 通知の閾値
score_threshold: 2
